### ISSUE TITLE
Fix the Search Bar and Add github Api

### ISSUE THREAD

**Issue by abdullah-dev5** [sagar-7227/GitHub-Profile-Finder#1]
While trying to search it does'nt work .fix the error and also add a button to search to Search 
and use Github user  Api  

use following method to fetch data.

fetch('https://api.github.com/users/{YOUR_USERNAME}')
    .then(response => response.json()) //Converting the response to a JSON object
    .then( data => console.log(data)) // Now you will be able to see the data on you browser console
    .catch( error => console.error(error));

**Comment by sagar-7227** [comment]
@abdullah-dev5 Thanks for your issue. It's simply because my GitHub token has expired. Now you can find it at https://sagar-github-finder.netlify.app/
